### ISSUE TITLE
Put ifconfig.io docker image on docker hub

### ISSUE THREAD

**Issue by Byh0ki** [georgyo/ifconfig.io#10]
Hello,

Do you plan to push this project as a docker image to hub.docker.com (or else) ? You don't even need a CI, you could ask Docker hub to build the image for you.

Regards,

Byh0ki

**Comment by georgyo** [comment]
Sure, why not: https://hub.docker.com/repository/docker/georgyo/ifconfig.io

**Comment by Byh0ki** [comment]
The next step would be to push a tag when there is a stable version or a milestone to create a release (and a tagged docker image). Like this we can expect the same behavior when we use the image with a specified tag!

Do you think it's possible for you ?

**Comment by georgyo** [comment]
This is a good idea. I don't use docker myself, the overhead is to great. But I could start tagging. Next commit I'll start tagging each deploy.

**Comment by Byh0ki** [comment]
Well, I'm usually behind a proxy so using the current image is not the best for the moment but I'll try to submit a PR (i don't know when) with an option to specify that ifconfig.io is running behind a proxy.

Do you have some benchmarks on the docker overhead ? I'm curious about the performance penalty

**Comment by georgyo** [comment]
I don't have any benchmarks, but ifconfig.io is currently get a little over a billion hits a day, which on average is ~11krps, from many thousands of clients, each creating and tearing down a new connection each and every time.

The way docker networking works, there would now be 3 additional systems required to handle that load.

The docker-proxy, which is listening on the host. - This one terminates one connection and creates a new one, essentially doubling the amount of connections alone.

The docker bridge creating the network overlay and then veth inside and outside the container. - These also require at least one, maybe two additional copies of the network traffic.

Almost all the system load comes from handling connections, not from the go process.

**Comment by Byh0ki** [comment]
"docker-proxy" is not really used (it's only a "catch all" and can be disabled without any problem on recent kernels), the traffic goes through netfilter and is DNATed to the appropriate container. Your point on the bridge is however valid :)
