### ISSUE TITLE
Which ccloud provider is recommended to deploy fast ?

### ISSUE THREAD

**Issue by Jackychans** [georgyo/ifconfig.io#13]
I know that the docker images could be deployed almost on any cloud provider (AWS, Azure, Digital Ocean and so on).
However, just want a recommendation of which cloud provider under what services is convinient to host and deploy the image, for example Azure App services, considering I wanna enable **Ipv6 address**  as well (when curl ipconfig.io/ip).

Thanks a lot

**Comment by georgyo** [comment]
I personally use linode for as I have been using them for almost a decade. Each instance comes with a fair amount of included bandwidth, so you don't get a surprise bill if you suddenly get some actual request traffic to your site.

It's also worth noting that I do not deploy ifconfig.io with docker or kubernetes. ifconfig.io is getting a little over a billion requests per day, and while docker networking is pretty great for normal traffic flows, this particular site would need 4 times as much computing power to run it under docker.
