### ISSUE TITLE
County code is blank

### ISSUE THREAD

**Issue by yanggis** [georgyo/ifconfig.io#16]
Just downloaded the latest version, compiled, and made it online.
Everything works fine, except that the country code empty.
Could you please help check what the problem is?
Many thanks.

**Comment by georgyo** [comment]
I'm currently cheating, I am not doing the country code lookup myself. Instead I am relying on the fact that cloudflare passes me that info in the headers it sends me.

You may be interested in a very similar project: https://github.com/mpolden/echoip

My service is currently handling 1 billion requests a day for $40/month. Actually doing the geoip lookup would greatly increase that cost.
