### ISSUE TITLE
More commandline-agent

### ISSUE THREAD

**Issue by kongsted** [georgyo/ifconfig.io#24]
Not really an issue - more a feature request, for this great system/website! :)

Would be great if it also would detect request coming from Powershell.

Cheers!

**Comment by georgyo** [comment]
Absolutely! Do you the user agent PowerShell uses?

The list of user agents we currently detect is here:
https://github.com/georgyo/ifconfig.io/blob/0395b2024d26ffa92cede56f456e4a784c45c4de/main.go#L247-L254

**Comment by dotysan** [comment]
> Absolutely! Do you the user agent PowerShell uses?

Just tested here.

```
GET /foo HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.19041.1682
Host: ...
```

**Comment by dotysan** [comment]
And with [Invoke-WebRequest 7.2](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.2)

```
User-Agent: Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.19044; en-US) PowerShell/7.2.4
```

**Comment by georgyo** [comment]
This is now live and tested. Let me know if you run into any issues.
