### ISSUE TITLE
workin through reverse proxy

### ISSUE THREAD

**Issue by fle108** [georgyo/ifconfig.io#3]
is there a way to make it work through reverse proxy like traefik or ingress ?

**Comment by georgyo** [comment]
Didn't see come in, but there are almost no config flags. If you are willing to edit the code, change `CF-Connecting-IP` to `X-Forwarded-For` should make it work with traefik and ingress.

https://github.com/georgyo/ifconfig.io/blob/2f4f8ce6c728212ea7b0de4dd2f4fdb2ea6b9ba0/main.go#L39

**Comment by soullivaneuh** [comment]
Can it be considered as an option?

We may indeed change a line of the code, but it would be much simpler to just use the official image instead of re-building it! :+1: 

As many docker setups use Traefik, I don't consider it very cumbersome.

What do you think?

**Comment by georgyo** [comment]
Now possible with `FORWARD_IP_HEADER` environment variable.
