### ISSUE TITLE
Logging/Privacy policy

### ISSUE THREAD

**Issue by user8446** [georgyo/ifconfig.io#31]
Hi,

Is there a logging/privacy policy for ifconfig.io? I'm looking for it to use for a work project.

Thank you for the development of ifconfig.io!

**Comment by georgyo** [comment]
Sorry, I didn't see this ticket get created.

I don't currently have a logging policy written down anywhere, but the code does not log at all and I do not write or keep any logs. At the current rate of 2 billion requests a day, that would be at least 50GB a day to keep the logs.

That said, the service is running behind cloudflare. I do not have access to the cloudflare logs, but they very likely exist.  Cloudflare does give me some very crude analytics, so I can see the number of requests and from which country they came from, which is all I care about.

**Comment by user8446** [comment]
Awesome, thank you!
