### ISSUE TITLE
Easier cURL command copy/paste

### ISSUE THREAD

**Issue by JeffAlyanak** [georgyo/ifconfig.io#32]
To make copying of the cURL commands a bit easier, would it make sense to update the template slightly to make the `$ `  unselectable?

This would only require a couple of small changes (and I'd be happy to put together the pull request if you think the change makes sense):

First, the addition of a bit of CSS. A minified version of:

```
.unselectable {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

Second, the wrapping of each `$ ` with a span of said class:

```
<span class="unselectable">$ </span>
```

With those changes the user could triple-click or drag select the command without risk of picking up the `$ `.

**Comment by georgyo** [comment]
Sounds good to me!

We also could remove the $ entirely
