### ISSUE TITLE
Support IPv4 and IPv6 subdomains

### ISSUE THREAD

**Issue by tibeer** [georgyo/ifconfig.io#36]
Hi!

First of all thanks a lot for this awesome project. My question is somewhat related to #6,
but without the ability of using _curl_. There are some software components out there (e.g. Hashicorps http provider)
that are not capable of directly selecting the IP version (like you can do with curl). Therefore it would be nice to have two sub-domains that are explicit for the IP version. If this is out of scope of this project, this is fine for me, too!

Regards Tim

**Comment by georgyo** [comment]
The biggest challenge is that cloudflare does not allow conditional setting of IPv6/IPv4. You always get both in DNS no matter what if it is behind cloudflare.

I used to have an unofficial 4.ifconfig.io and 6.ifconfig.io, however migrating everything to k8s has made it so my stack no longer has native ipv6. 

4.ifconfig.io still exists, but I cannot currently have a functioning v6 subdomain. 

Side note: Migrating my personal projects to k8s has doubled my costs and halved my performance

**Comment by tibeer** [comment]
Thanks a lot!
