### ISSUE TITLE
curl is no working with cloudflare tunnel

### ISSUE THREAD

**Issue by ansred** [georgyo/ifconfig.io#46]
Curl commands don't not work when you host the docker container with a cloudflare tunnel.

Only the webpage works fine

Is that expected?

**Comment by georgyo** [comment]
Can you give me the output of `https://ifconfig.io/headers.json`, or the same endpoint from your instance?

**Comment by ansred** [comment]
@georgyo sure is it

btw, when I do curl with https full url and path, it works.

but not with direct curl fqdn


`{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"Accept-Encoding":["gzip"],"Accept-Language":["en-US,en;q=0.9"],"Cdn-Loop":["cloudflare"],"Cf-Connecting-Ip":["172.98.00.00"],"Cf-Ipcountry":["CA"],"Cf-Ray":["7ce727d3ace353dd-YYZ"],"Cf-Visitor":["{\"scheme\":\"https\"}"],"Cf-Warp-Tag-Id":["88785937-4573-4d0a-9529-e04f4a5863c0"],"Connection":["keep-alive"],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-Site":["none"],"User-Agent":["Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/113.0.5672.121 Mobile/15E148 Safari/604.1"],"X-Forwarded-For":["172.98.00.00"],"X-Forwarded-Proto":["https"]} `

**Comment by badguy2003st** [comment]
The issue is, that curl by default doesn't follow redirects (which cloudflare does). You just have to add the -L parameter to enforce it (example: "curl  [url] -L"). Maybe you can change it in the template since it shouldn't have negative consequences.

**Comment by ansred** [comment]
@badguy2003st the -L option work and did the trick. Thanks man!
