### ISSUE TITLE
Support for switch between IPv4 and IPv6

### ISSUE THREAD

**Issue by dabde** [georgyo/ifconfig.io#6]
Hi,

think it's not a source code related issue. But from my ISP, I get both IPv4 and IPv6. For some Firewalls, I need somehow my IPv4 Address. But a simple curl call is return my IPv6 address.

Related to this, more a request, if you can setup additional DNS Entries to have

ipv4.ifconfig.io -> only with ipv4 IP's
ipv6.ifconfig.io -> only with ipv6 IP's

the code would already do the correct thing.

```
$ curl 104.24.123.146 -H "Host: ifconfig.io"
xxx.xxx.xxx.xxx
```

```
$ curl http://\[2606:4700:3030::ac43:bd66\] -H "Host: ifconfig.io"
xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
```

thanks

**Comment by georgyo** [comment]
Thanks for the suggestion!

I have played around with this in the past, however it's much easier to force your cli tool to use the protocol you care about it.

```
curl -4 ifconfig.io
curl -6 ifconfig.io
```

Where you cannot do this easily is with a browser. Having the protocol specific domains there would be useful, but I cannot implement this currently.

I have become somewhat depended on cloudflare for connection pooling, and there is no way to have a service behind cloudflare that only exposes ip4 or ip6 addresses.

**Comment by dabde** [comment]
Ahhh thx. Didn't think about the curl arguments.
