### ISSUE TITLE
Curl Missing parameter

### ISSUE THREAD

**Issue by amanjuman** [georgyo/ifconfig.io#66]
I hosted the Docker Container. Behind NAT, it was configured through HAProxy.
Whenever I open the web page, it's showing everything as usual. However, when I'm doing curl fqdn.domain.tld
In that case, I'm getting a Missing parameter error.

Interestingly when I perform curl https://fqdn.domain.tld it works fine.
What could be the possible issue?

**Comment by georgyo** [comment]
Can you give the full error?  Maybe the full output of `curl -i fqdn.domain.tld`?

The code for this thing is very small, there and there are no parameters at all. I don't even have an arg parser: https://github.com/georgyo/ifconfig.io/blob/master/main.go

**Comment by amanjuman** [comment]
```
HTTP/1.1 400 Bad Request
Date: Sun, 04 Feb 2024 14:17:17 GMT
Content-Length: 17
Content-Type: text/plain; charset=utf-8
```

**Comment by georgyo** [comment]
I believe your HAProxy config is generating that error. We don't throw 400 errors at all. 404 sure, but never 400.

**Comment by amanjuman** [comment]
I'm getting this on the Host VM.
```
root@vm:~# curl -I 192.168.1.199:3005
HTTP/1.1 404 Not Found
Content-Type: text/plain
Date: Sun, 04 Feb 2024 14:52:43 GMT
Content-Length: 18
```
Docker Ports:
0.0.0.0:3005->8080/tcp, :::3005->8080/tcp

**Comment by georgyo** [comment]
I don't think I have enough insight to debug your setup. I don't use docker or haproxy, and I don't understand how you could be getting these errors.
