### ISSUE TITLE
https://ifconfig.io is DOWN

### ISSUE THREAD

**Issue by sandeep-ongit** [georgyo/ifconfig.io#81]
Hey,
This is to update you that https://ifconfig.io is DOWN.
Below is error.

![image](https://github.com/user-attachments/assets/f9c9debe-b032-49c7-8c3c-fa77afc51733)

**Comment by georgyo** [comment]
Looks like it went down around 8PM EST yesterday. It should have failed over automatically... I'll look into that.

In any case it is back up now.

**Comment by sandeep-ongit** [comment]
Yes, it works
